# Generated by Django 4.2.30 on 2026-07-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_contribution_remove_expense_is_settled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
    ]
