# Generated by Django 4.2.30 on 2026-07-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
    ]
