# Generated by Django 4.2.30 on 2026-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='currency',
            field=models.CharField(choices=[('NPR', 'Nepalese Rupee (NPR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('INR', 'Indian Rupee (INR)'), ('GBP', 'British Pound (GBP)'), ('AUD', 'Australian Dollar (AUD)'), ('CAD', 'Canadian Dollar (CAD)'), ('SGD', 'Singapore Dollar (SGD)')], default='NPR', max_length=3),
        ),
    ]
